version: "3.8"
services:
  app:
    container_name: summary-app
    restart: unless-stopped
    env_file:
      - .env
    # environment:
    #   PGHOST: 'db'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    expose:
      - ${PORT}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: curl --fail -s http://localhost:${PORT}/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command:
      [
        "uvicorn",
        "main:app",
        "--proxy-headers",
        "--host",
        "0.0.0.0",
        "--port",
        "${PORT}",
        "--workers",
        "1",
      ]
