version: '3.8'
services:
  app:
    container_name: summary-app
    restart: unless-stopped
    # env_file:
    #   - .env
    # environment:
    #   PGHOST: 'db'
    #   PGDATABASE: ${DATABASE_NAME}
    #   PGUSER: ${DATABASE_USER}
    #   PGPASSWORD: ${DATABASE_PASS}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    healthcheck:
      test: curl --fail -s http://localhost:8000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: ["uvicorn","main:app","--proxy-headers","--host","0.0.0.0","--port","8000","--workers","3"]


 