name: Deploy by Runner

on:
  workflow_run:
    workflows: ["Tests", "Docker Build"]
    branches: ["prod"]
    types:
      - completed

env:
  PORT: 6001

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        run: docker compose down
      - name: Remove unused data
        run: docker system prune -a -f
      - name: Cleanup build folder
        run: |
          rm -rf ./* || true

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Create env file
        run: |
          touch config.env
          echo SITE_KEY=${{ secrets.SITE_KEY }} >> config.env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> config.env
          echo API_USER=${{ secrets.API_USER }} >> config.env
          echo API_PWD=${{ secrets.API_PWD }} >> config.env
          echo API_KEY=${{ secrets.API_KEY }} >> config.env

          echo CAPTCHA1=${{ secrets.CAPTCHA1 }} >> config.env
          echo CAPTCHA2=${{ secrets.CAPTCHA2 }} >> config.env
          echo CAPTCHA3=${{ secrets.CAPTCHA3 }} >> config.env
          echo CAPTCHA4=${{ secrets.CAPTCHA4 }} >> config.env
          echo CAPTCHA5=${{ secrets.CAPTCHA5 }} >> config.env

          echo PORT=${{ env.PORT }} >> config.env

      - name: Create docker-compose
        run: |
          touch docker-compose.yml
          echo -e "version: \"3.8\"" >> docker-compose.yml
          echo -e "services: " >> docker-compose.yml
          echo -e "  TextSummary: " >> docker-compose.yml
          echo -e "    image: registry.frants.site/textsummary:latest" >> docker-compose.yml
          echo -e "    env_file: config.env" >> docker-compose.yml
      - name: Run docker-compose
        run: docker compose up -d
